from __future__ import annotations

import re
import shlex
import stat
import subprocess
from datetime import date
from pathlib import Path

import pytest

import scripts.check_dependency_contract as dependency_contract
from scripts.check_dependency_contract import (
    BOOTSTRAP_SOURCE_FILES,
    COMPILE_SCRIPT_COMMAND,
    COMPATIBILITY_CONSTRAINTS_FILE,
    FORBIDDEN_CONTAINER_DEV_DEPENDENCIES,
    LOCK_COMMANDS,
    REQUIRED_COMPATIBILITY_CONSTRAINTS,
    REQUIRED_CONTAINER_DEPENDENCIES,
    REQUIRED_DEV_DEPENDENCIES,
    REQUIRED_SECURITY_CONSTRAINTS,
    REQUIRED_UNSAFE_PINS,
    SECURITY_CONSTRAINTS_FILE,
    UNSAFE_OMISSION_FOOTER,
    UPSTREAM_WARNING_MESSAGE,
    UPSTREAM_WARNING_MESSAGE_PATTERN,
    UPSTREAM_WARNING_CATEGORY,
    UPSTREAM_WARNING_MODULE_PATTERN,
    UPSTREAM_WARNING_POLICY_FILTER,
    check_dependency_contract,
    collect_dependency_contract_errors,
    compile_requirement_locks,
    main,
    verify_bootstrap_compilation,
)


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SECURITY_FIXTURE_PINS = {
    "aiohttp": "3.14.1",
    "cloakbrowser": "0.3.28",
    "cryptography": "48.0.1",
    "fastapi": "0.139.0",
    "idna": "3.18",
    "langchain": "1.3.9",
    "langsmith": "0.8.18",
    "mistune": "3.3.0",
    "nltk": "3.10.0",
    "pydantic-settings": "2.14.2",
    "pypdf": "6.13.3",
    "python-multipart": "0.0.31",
    "starlette": "1.3.1",
    "weasyprint": "69.0",
}
RUNTIME_SECURITY_PACKAGES = {
    "cloakbrowser",
    "fastapi",
    "idna",
    "pydantic-settings",
    "python-multipart",
    "starlette",
}
LOCK_UNSAFE_PINS = {
    "requirements.txt": ["setuptools==83.0.0"],
    "requirements-dev.txt": ["pip==26.1.2", "setuptools==83.0.0"],
    "requirements-research.txt": ["setuptools==83.0.0"],
    "requirements-container.txt": ["setuptools==83.0.0"],
}
COMPATIBILITY_FIXTURE_CONSTRAINTS = {"requests": "<2.34"}


def _lock_header() -> str:
    return "\n".join(
        (
            "#",
            "# This file is autogenerated by pip-compile with Python 3.12",
            "# by the following command:",
            "#",
            f"#    {COMPILE_SCRIPT_COMMAND}",
            "#",
        )
    )


def _hashed_lock_lines(pins: list[str]) -> list[str]:
    digest = "0" * 64
    lines: list[str] = []
    for pin in pins:
        lines.extend((f"{pin} \\", f"    --hash=sha256:{digest}"))
    return lines


def _write_contract_fixture(root: Path) -> None:
    package_dir = root / "llm_gateway_core"
    package_dir.mkdir(parents=True)
    (package_dir / "__init__.py").write_text("", encoding="utf-8")
    (package_dir / "version.py").write_text(
        '__version__ = "1.10.0"\n',
        encoding="utf-8",
    )
    (root / "pyproject.toml").write_text(
        f"""
[project]
dependencies = ["httpx>=0.28.0"]

[build-system]
requires = ["setuptools==83.0.0", "wheel==0.47.0"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
dev = [
    "gpt-researcher>=0.14.8,<0.15.0",
    "httpx2>=2.5.0",
    "pip-audit>=2.9.0",
    "pip-tools>=7.5.3",
    "pytest>=9.0",
    "pytest-cov>=6.0",
    "pytest-playwright>=0.7.2",
]
research = ["gpt-researcher>=0.14.8,<0.15.0"]

[tool.pytest.ini_options]
markers = ["browser: browser tests"]
filterwarnings = [
    "error::DeprecationWarning",
    '{UPSTREAM_WARNING_POLICY_FILTER}',
]

[[tool.llmgateway.upstream-warning-policy]]
id = "gpt-researcher-langchain-community"
package = "gpt-researcher"
package_version = "0.14.8"
expires = 2026-10-11
filter = '{UPSTREAM_WARNING_POLICY_FILTER}'
reason = "upstream still imports the deprecated integration"
""".strip()
        + "\n",
        encoding="utf-8",
    )
    security_pins = [
        f"{name}=={version}"
        for name, version in SECURITY_FIXTURE_PINS.items()
    ]
    runtime_security_pins = [
        f"{name}=={SECURITY_FIXTURE_PINS[name]}"
        for name in sorted(RUNTIME_SECURITY_PACKAGES)
    ]
    (root / SECURITY_CONSTRAINTS_FILE).write_text(
        "\n".join(security_pins) + "\n",
        encoding="utf-8",
    )
    (root / COMPATIBILITY_CONSTRAINTS_FILE).write_text(
        "\n".join(
            f"{name}{specifier}"
            for name, specifier in COMPATIBILITY_FIXTURE_CONSTRAINTS.items()
        )
        + "\n",
        encoding="utf-8",
    )
    research_pins = [
        "gpt-researcher==0.14.8",
        "httpx==0.28.1",
        "playwright==1.58.0",
        "requests==2.33.1",
        *security_pins,
        *LOCK_UNSAFE_PINS["requirements-research.txt"],
    ]
    lock_contents = {
        "requirements.txt": [
            "httpx==0.28.1",
            "requests==2.33.1",
            *runtime_security_pins,
            *LOCK_UNSAFE_PINS["requirements.txt"],
        ],
        "requirements-dev.txt": [
            "httpx==0.28.1",
            *security_pins,
            "gpt-researcher==0.14.8",
            "httpx2==2.5.0",
            "pip-audit==2.9.0",
            "pip-tools==7.5.3",
            "pytest==9.0.3",
            "pytest-cov==6.0.0",
            "pytest-playwright==0.7.2",
            "requests==2.33.1",
            "wheel==0.47.0",
            *LOCK_UNSAFE_PINS["requirements-dev.txt"],
        ],
        "requirements-research.txt": research_pins,
        "requirements-container.txt": _hashed_lock_lines(research_pins),
    }
    for filename, pins in lock_contents.items():
        (root / filename).write_text(
            _lock_header() + "\n" + "\n".join(pins) + "\n",
            encoding="utf-8",
        )

    for filename in ("README.md", "README_EN.MD"):
        (root / filename).write_text(COMPILE_SCRIPT_COMMAND + "\n", encoding="utf-8")


def test_repository_dependency_contract_is_consistent() -> None:
    check_dependency_contract(PROJECT_ROOT)


def test_contract_rejects_build_system_pin_drift_from_dev_lock(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "setuptools==83.0.0",
            "setuptools==82.0.1",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert (
        "Build-system pin mismatch for setuptools: "
        "pyproject.toml=82.0.1, requirements-dev.txt=83.0.0"
    ) in errors


def test_contract_rejects_unpinned_build_system_dependency(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            "wheel==0.47.0",
            "wheel>=0.47.0",
            1,
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(
        "must exactly pin build dependency 'wheel'" in error for error in errors
    )


def test_contract_rejects_missing_pytest_playwright_declaration(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            '    "pytest-playwright>=0.7.2",\n',
            "",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("Missing required development dependencies" in error for error in errors)


def test_required_ci_tools_are_part_of_the_dev_contract() -> None:
    assert REQUIRED_DEV_DEPENDENCIES == {
        "httpx2",
        "pip-audit",
        "pip-tools",
        "pytest-cov",
        "pytest-playwright",
    }


def test_upstream_warning_policy_expires_automatically(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)

    errors = collect_dependency_contract_errors(
        tmp_path,
        as_of=date(2026, 10, 12),
    )

    assert any("Upstream warning policy expired on 2026-10-11" in error for error in errors)


def test_contract_rejects_warning_filter_drift(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            UPSTREAM_WARNING_POLICY_FILTER,
            "ignore::DeprecationWarning",
            1,
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("filterwarnings must reject all deprecation warnings" in error for error in errors)


def test_contract_rejects_warning_policy_package_version_drift(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'package_version = "0.14.8"',
            'package_version = "0.14.7"',
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(
        "package_version does not match requirements-dev.txt: 0.14.7 != 0.14.8" in error
        for error in errors
    )


def test_upstream_warning_filter_matches_only_the_full_message() -> None:
    fields = UPSTREAM_WARNING_POLICY_FILTER.split(":")

    assert len(fields) == 4
    assert fields[1] == UPSTREAM_WARNING_MESSAGE_PATTERN
    assert fields[2] == UPSTREAM_WARNING_CATEGORY == "DeprecationWarning"
    assert fields[3] == UPSTREAM_WARNING_MODULE_PATTERN
    assert fields[3] == r"^gpt_researcher\.scraper\.arxiv\.arxiv$"
    assert r"\x3a" in fields[1]
    assert ":" not in fields[1]
    assert re.fullmatch(fields[1], UPSTREAM_WARNING_MESSAGE)
    assert not re.fullmatch(fields[1], UPSTREAM_WARNING_MESSAGE + " unexpected suffix")
    assert not re.fullmatch(
        fields[1],
        UPSTREAM_WARNING_MESSAGE.replace("sunset", "deprecated"),
    )


def test_required_security_pins_are_part_of_the_contract() -> None:
    assert REQUIRED_SECURITY_CONSTRAINTS == set(SECURITY_FIXTURE_PINS)
    required_flags = {
        "--allow-unsafe",
        f"--constraint={SECURITY_CONSTRAINTS_FILE}",
        f"--constraint={COMPATIBILITY_CONSTRAINTS_FILE}",
    }
    assert all(required_flags <= set(shlex.split(command)) for command in LOCK_COMMANDS.values())
    assert all("--upgrade" not in shlex.split(command) for command in LOCK_COMMANDS.values())
    assert REQUIRED_UNSAFE_PINS == {
        filename: frozenset(pin.split("==", 1)[0] for pin in pins)
        for filename, pins in LOCK_UNSAFE_PINS.items()
    }
    assert "--generate-hashes" in shlex.split(
        LOCK_COMMANDS["requirements-container.txt"]
    )
    assert all(
        "--generate-hashes" not in shlex.split(command)
        for filename, command in LOCK_COMMANDS.items()
        if filename != "requirements-container.txt"
    )


def test_container_lock_contract_has_only_production_dependencies() -> None:
    assert REQUIRED_CONTAINER_DEPENDENCIES == {
        "cloakbrowser",
        "gpt-researcher",
        "playwright",
    }
    assert FORBIDDEN_CONTAINER_DEV_DEPENDENCIES == {
        "httpx2",
        "pip-audit",
        "pip-tools",
        "pytest",
        "pytest-cov",
        "pytest-playwright",
        "ruff",
    }


def test_contract_rejects_unhashed_container_pin(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8").replace(
            f"    --hash=sha256:{'0' * 64}\n",
            "",
            1,
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("active pins without SHA-256 hashes" in error for error in errors)


def test_contract_rejects_hash_after_noncontinued_requirement(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8").replace(
            "gpt-researcher==0.14.8 \\",
            "gpt-researcher==0.14.8",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("has a hash without a continued requirement" in error for error in errors)


@pytest.mark.parametrize("interruption", ("\n", "    # unexpected comment\n"))
def test_contract_rejects_interrupted_hash_continuation(
    tmp_path: Path,
    interruption: str,
) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8").replace(
            "gpt-researcher==0.14.8 \\\n",
            "gpt-researcher==0.14.8 \\\n" + interruption,
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("interrupts an open hash continuation" in error for error in errors)


def test_contract_rejects_dangling_requirement_continuation_at_eof(
    tmp_path: Path,
) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8") + "dangling==1.0.0 \\",
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("ends with an open hash continuation" in error for error in errors)


def test_contract_rejects_dangling_hash_continuation_at_eof(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8")
        + "dangling==1.0.0 \\\n"
        + f"    --hash=sha256:{'0' * 64} \\",
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("ends with an open hash continuation" in error for error in errors)


def test_contract_consumes_complete_hash_block_for_inactive_marker(
    tmp_path: Path,
) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8")
        + 'inactive-only==1.0.0 ; python_version < "3.0" \\\n'
        + f"    --hash=sha256:{'1' * 64} \\\n"
        + f"    --hash=sha256:{'2' * 64}\n",
        encoding="utf-8",
    )

    assert collect_dependency_contract_errors(tmp_path) == []


def test_contract_allows_pip_compile_comment_after_closed_hash(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    hash_line = f"    --hash=sha256:{'0' * 64}\n"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8").replace(
            hash_line,
            hash_line + "    # via gpt-researcher\n",
            1,
        ),
        encoding="utf-8",
    )

    assert collect_dependency_contract_errors(tmp_path) == []


def test_contract_rejects_container_pin_version_drift(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8").replace(
            "httpx==0.28.1",
            "httpx==0.28.0",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("Container pin mismatch for httpx" in error for error in errors)


@pytest.mark.parametrize(
    "package_name",
    sorted(FORBIDDEN_CONTAINER_DEV_DEPENDENCIES),
)
def test_contract_rejects_development_dependency_in_container_lock(
    tmp_path: Path,
    package_name: str,
) -> None:
    _write_contract_fixture(tmp_path)
    container_lock = tmp_path / "requirements-container.txt"
    container_lock.write_text(
        container_lock.read_text(encoding="utf-8")
        + f"{package_name}==1.0.0 \\\n"
        + f"    --hash=sha256:{'0' * 64}\n",
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(
        f"development-only dependencies: {package_name}" in error for error in errors
    )
    assert any(
        f"outside the research production closure: {package_name}" in error
        for error in errors
    )


def test_required_compatibility_bound_is_semantic_not_an_exact_lock_pin() -> None:
    assert REQUIRED_COMPATIBILITY_CONSTRAINTS == COMPATIBILITY_FIXTURE_CONSTRAINTS
    assert REQUIRED_COMPATIBILITY_CONSTRAINTS["requests"] == "<2.34"


def test_contract_rejects_missing_security_constraints_file(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    (tmp_path / SECURITY_CONSTRAINTS_FILE).unlink()

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(f"Cannot read {SECURITY_CONSTRAINTS_FILE}" in error for error in errors)


def test_contract_rejects_missing_compatibility_constraints_file(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    (tmp_path / COMPATIBILITY_CONSTRAINTS_FILE).unlink()

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(f"Cannot read {COMPATIBILITY_CONSTRAINTS_FILE}" in error for error in errors)


def test_contract_rejects_compatibility_boundary_drift_to_exact_pin(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    constraints = tmp_path / COMPATIBILITY_CONSTRAINTS_FILE
    constraints.write_text("requests==2.33.1\n", encoding="utf-8")

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(
        "must declare the reviewed compatibility boundary requests<2.34" in error
        for error in errors
    )


def test_contract_rejects_lock_outside_compatibility_boundary(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    runtime_lock = tmp_path / "requirements.txt"
    runtime_lock.write_text(
        runtime_lock.read_text(encoding="utf-8").replace(
            "requests==2.33.1",
            "requests==2.34.2",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(
        "Compatibility constraint mismatch for requests: "
        "compatibility-constraints.txt=<2.34, requirements.txt=2.34.2" in error
        for error in errors
    )


def test_contract_rejects_unpinned_security_constraint(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    constraints = tmp_path / SECURITY_CONSTRAINTS_FILE
    constraints.write_text(
        constraints.read_text(encoding="utf-8").replace(
            "aiohttp==3.14.1",
            "aiohttp>=3.14.1",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(
        f"{SECURITY_CONSTRAINTS_FILE}:1 must contain one exact == pin" in error
        for error in errors
    )


def test_contract_rejects_security_constraint_lock_mismatch(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    dev_lock = tmp_path / "requirements-dev.txt"
    dev_lock.write_text(
        dev_lock.read_text(encoding="utf-8").replace(
            "aiohttp==3.14.1",
            "aiohttp==3.14.0",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("Security constraint mismatch for aiohttp" in error for error in errors)


def test_contract_rejects_compile_command_without_security_constraints(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setitem(
        dependency_contract.LOCK_COMMANDS,
        "requirements.txt",
        f"pip-compile --allow-unsafe --constraint={COMPATIBILITY_CONSTRAINTS_FILE} "
        "--output-file=requirements.txt --strip-extras pyproject.toml",
    )
    _write_contract_fixture(tmp_path)

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(SECURITY_CONSTRAINTS_FILE in error for error in errors)


def test_contract_rejects_compile_command_without_compatibility_constraints(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setitem(
        dependency_contract.LOCK_COMMANDS,
        "requirements.txt",
        f"pip-compile --allow-unsafe --constraint={SECURITY_CONSTRAINTS_FILE} "
        "--output-file=requirements.txt --strip-extras pyproject.toml",
    )
    _write_contract_fixture(tmp_path)

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(COMPATIBILITY_CONSTRAINTS_FILE in error for error in errors)


def test_contract_rejects_compile_command_without_allow_unsafe(
    tmp_path: Path,
    monkeypatch,
) -> None:
    monkeypatch.setitem(
        dependency_contract.LOCK_COMMANDS,
        "requirements.txt",
        f"pip-compile --constraint={SECURITY_CONSTRAINTS_FILE} "
        f"--constraint={COMPATIBILITY_CONSTRAINTS_FILE} "
        "--output-file=requirements.txt --strip-extras pyproject.toml",
    )
    _write_contract_fixture(tmp_path)

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("--allow-unsafe" in error for error in errors)


def test_contract_rejects_unsafe_omission_footer(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    dev_lock = tmp_path / "requirements-dev.txt"
    dev_lock.write_text(
        dev_lock.read_text(encoding="utf-8")
        + f"\n{UNSAFE_OMISSION_FOOTER}\n# pip\n# setuptools\n",
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("requirements-dev.txt contains the pip-compile unsafe-omission footer" in error for error in errors)


@pytest.mark.parametrize(
    ("filename", "pin"),
    (
        ("requirements.txt", "setuptools==83.0.0"),
        ("requirements-dev.txt", "pip==26.1.2"),
        ("requirements-research.txt", "setuptools==83.0.0"),
        ("requirements-container.txt", "setuptools==83.0.0"),
    ),
)
def test_contract_rejects_missing_required_unsafe_pin(
    tmp_path: Path,
    filename: str,
    pin: str,
) -> None:
    _write_contract_fixture(tmp_path)
    lock = tmp_path / filename
    content = lock.read_text(encoding="utf-8")
    lock.write_text(
        content.replace(f"{pin}\n", "").replace(f"{pin} \\\n", ""),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(f"{filename} is missing required active unsafe pins" in error for error in errors)


def test_contract_rejects_missing_browser_marker_registration(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'markers = ["browser: browser tests"]',
            "markers = []",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert "Missing required pytest markers: browser" in errors


def test_contract_rejects_pin_outside_declared_range(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace("httpx>=0.28.0", "httpx>=1.0"),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("does not satisfy >=1.0" in error for error in errors)


def test_contract_keeps_research_only_dependency_out_of_runtime(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    pyproject = tmp_path / "pyproject.toml"
    pyproject.write_text(
        pyproject.read_text(encoding="utf-8").replace(
            'dependencies = ["httpx>=0.28.0"]',
            'dependencies = ["httpx>=0.28.0", "gpt-researcher>=0.14.8,<0.15.0"]',
        ),
        encoding="utf-8",
    )
    runtime_lock = tmp_path / "requirements.txt"
    runtime_lock.write_text(
        runtime_lock.read_text(encoding="utf-8") + "gpt-researcher==0.14.8\n",
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("must not be declared as runtime" in error for error in errors)
    assert any("must not be pinned in requirements.txt" in error for error in errors)


def test_contract_rejects_shared_pin_drift(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    research_lock = tmp_path / "requirements-research.txt"
    research_lock.write_text(
        research_lock.read_text(encoding="utf-8").replace("httpx==0.28.1", "httpx==0.28.0"),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("Shared pin mismatch for httpx" in error for error in errors)


def test_inactive_lock_marker_cannot_satisfy_active_direct_dependency(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    dev_lock = tmp_path / "requirements-dev.txt"
    dev_lock.write_text(
        dev_lock.read_text(encoding="utf-8").replace(
            "pytest-playwright==0.7.2",
            'pytest-playwright==0.7.2 ; python_version < "3.0"',
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any(
        "missing an active pin for direct dependency 'pytest-playwright'" in error
        for error in errors
    )


def test_active_lock_marker_satisfies_active_direct_dependency(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    dev_lock = tmp_path / "requirements-dev.txt"
    dev_lock.write_text(
        dev_lock.read_text(encoding="utf-8").replace(
            "pytest-playwright==0.7.2",
            'pytest-playwright==0.7.2 ; python_version >= "3.12"',
        ),
        encoding="utf-8",
    )

    assert collect_dependency_contract_errors(tmp_path) == []


def test_static_checker_does_not_claim_transitive_resolver_closure(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)

    # The fixture intentionally omits httpx transitives such as httpcore. The
    # static checker validates direct pins; compile + clean install + pip check
    # own resolver closure.
    assert collect_dependency_contract_errors(tmp_path) == []


def test_contract_rejects_noncanonical_header(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    dev_lock = tmp_path / "requirements-dev.txt"
    dev_lock.write_text(
        dev_lock.read_text(encoding="utf-8").replace(
            COMPILE_SCRIPT_COMMAND,
            "./scripts/compile_other.sh",
        ),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("requirements-dev.txt header command differs" in error for error in errors)


def test_contract_rejects_unpinned_lock_entry(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    dev_lock = tmp_path / "requirements-dev.txt"
    dev_lock.write_text(
        dev_lock.read_text(encoding="utf-8").replace("pytest==9.0.3", "pytest>=9.0.3"),
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("must contain one exact == pin" in error for error in errors)


def test_cli_returns_nonzero_for_invalid_contract(tmp_path: Path, capsys) -> None:
    _write_contract_fixture(tmp_path)
    (tmp_path / "README_EN.MD").write_text("missing commands\n", encoding="utf-8")

    exit_code = main(["--root", str(tmp_path)])

    assert exit_code == 1
    assert "README_EN.MD must call the canonical dependency entrypoint" in capsys.readouterr().err


def test_contract_rejects_alternative_pip_compile_command_in_readme(tmp_path: Path) -> None:
    _write_contract_fixture(tmp_path)
    readme = tmp_path / "README.md"
    readme.write_text(
        readme.read_text(encoding="utf-8")
        + "```bash\npip-compile --upgrade pyproject.toml\n```\n",
        encoding="utf-8",
    )

    errors = collect_dependency_contract_errors(tmp_path)

    assert any("README.md duplicates pip-compile commands" in error for error in errors)


def test_compile_runs_canonical_commands_in_dependency_order(tmp_path: Path, monkeypatch) -> None:
    _write_contract_fixture(tmp_path)
    calls: list[tuple[list[str], Path, bool, dict[str, str]]] = []

    def fake_run(argv, *, cwd, check, env):
        calls.append((argv, cwd, check, env))

    monkeypatch.setattr(dependency_contract.subprocess, "run", fake_run)

    compile_requirement_locks(
        tmp_path,
        pip_compile_executable="/tools/pip-compile",
    )

    expected_argv = []
    for command in LOCK_COMMANDS.values():
        argv = shlex.split(command)
        argv[0] = "/tools/pip-compile"
        expected_argv.append(argv)
    assert [call[0] for call in calls] == expected_argv
    assert all(call[1:3] == (tmp_path, True) for call in calls)
    assert all(call[3]["CUSTOM_COMPILE_COMMAND"] == COMPILE_SCRIPT_COMMAND for call in calls)


def test_bootstrap_compile_uses_source_only_temporary_root(
    tmp_path: Path,
    monkeypatch,
) -> None:
    _write_contract_fixture(tmp_path)
    original_locks = {
        filename: (tmp_path / filename).read_text(encoding="utf-8")
        for filename in LOCK_COMMANDS
    }
    calls: list[tuple[Path, str | None]] = []

    def fake_compile(root: Path, *, pip_compile_executable: str | None = None) -> None:
        calls.append((root, pip_compile_executable))
        assert root != tmp_path
        assert all((root / filename).is_file() for filename in BOOTSTRAP_SOURCE_FILES)
        assert (root / "llm_gateway_core" / "version.py").read_text(
            encoding="utf-8"
        ) == (tmp_path / "llm_gateway_core" / "version.py").read_text(encoding="utf-8")
        assert all(not (root / filename).exists() for filename in LOCK_COMMANDS)

    monkeypatch.setattr(dependency_contract, "compile_requirement_locks", fake_compile)

    verify_bootstrap_compilation(
        tmp_path,
        pip_compile_executable="/tools/pip-compile",
    )

    assert len(calls) == 1
    assert calls[0][1] == "/tools/pip-compile"
    assert {
        filename: (tmp_path / filename).read_text(encoding="utf-8")
        for filename in LOCK_COMMANDS
    } == original_locks


def test_bootstrap_compile_fails_when_dynamic_version_source_is_missing(
    tmp_path: Path,
) -> None:
    _write_contract_fixture(tmp_path)
    (tmp_path / "llm_gateway_core" / "version.py").unlink()

    with pytest.raises(
        dependency_contract.DependencyCompilationError,
        match=r"missing source input llm_gateway_core/version.py",
    ):
        verify_bootstrap_compilation(
            tmp_path,
            pip_compile_executable="/tools/pip-compile",
        )


def test_compile_is_fail_fast(tmp_path: Path, monkeypatch) -> None:
    _write_contract_fixture(tmp_path)
    calls = 0

    def fake_run(argv, *, cwd, check, env):
        nonlocal calls
        calls += 1
        if calls == 2:
            raise subprocess.CalledProcessError(2, argv)

    monkeypatch.setattr(dependency_contract.subprocess, "run", fake_run)

    with pytest.raises(dependency_contract.DependencyCompilationError):
        compile_requirement_locks(
            tmp_path,
            pip_compile_executable="/tools/pip-compile",
        )

    assert calls == 2


def test_compile_shell_is_executable_thin_entrypoint() -> None:
    script = PROJECT_ROOT / "scripts" / "compile_requirements.sh"
    content = script.read_text(encoding="utf-8")

    assert script.stat().st_mode & stat.S_IXUSR
    assert "--compile" in content
    assert "pip-compile" not in content


def test_readmes_do_not_duplicate_canonical_commands() -> None:
    for filename in ("README.md", "README_EN.MD"):
        content = (PROJECT_ROOT / filename).read_text(encoding="utf-8")
        assert COMPILE_SCRIPT_COMMAND in content
        assert all(command not in content for command in LOCK_COMMANDS.values())
