"""Backward-compatible facade for gateway configuration loading."""

from .loading import (  # noqa: F401
    OPTIONAL_CONFIG_SHAPES,
    UTF8_BOM,
    _ConfigLoaderCore,
    _resolve_application_root,
    _resolve_config_path,
)
from .schema_validation import (  # noqa: F401
    AUDIO_SPEECH_DEFAULT_TARGET_PATH,
    AUDIO_TRANSCRIPTIONS_DEFAULT_TARGET_PATH,
    FORBIDDEN_OPERATION_BODY_PARAMS,
    IMAGES_EDITS_DEFAULT_TARGET_PATH,
    PDF_CONVERSIONS_DEFAULT_TARGET_PATH,
    RERANK_DEFAULT_TARGET_PATH,
    REQUEST_FORMAT_NVIDIA_GENAI_JSON,
    REQUEST_FORMAT_NVIDIA_RIVA_GRPC,
    REQUEST_FORMAT_OPENAI_IMAGES,
    REQUEST_FORMAT_OPENAI_IMAGES_MULTIPART,
    REQUEST_FORMAT_QUERY_PASSAGES,
    REQUEST_FORMAT_QUERY_TEXTS,
    RESPONSE_FORMAT_NVIDIA_ARTIFACTS,
    RESPONSE_FORMAT_OPENAI_IMAGES,
    RESPONSE_FORMAT_RANKINGS_LOGIT,
    RESPONSE_FORMAT_SCORES,
    RESPONSE_OUTPUT_FORMAT_JINA_RESULTS,
    SECURITY_HEADERS,
    SUPPORTED_REQUEST_FORMATS,
    SUPPORTED_RESPONSE_FORMATS,
    SUPPORTED_RESPONSE_OUTPUT_FORMATS,
)
from .schemas import (  # noqa: F401
    FUSION_PANEL_MAX,
    AudioSpeechModelConfig,
    AudioTranscriptionModelConfig,
    EmbeddingsModelConfig,
    FallbackModelRule,
    FusionMember,
    FusionModelConfig,
    FusionWebToolsConfig,
    ImagesEditModelConfig,
    ImagesGenerationModelConfig,
    ModelFallbackConfig,
    ModelPrefixRule,
    ModelRulesConfig,
    ModelsOperationConfig,
    OperationCostCalculatorConfig,
    OperationRoute,
    PayloadTransformConfig,
    PdfConversionModelConfig,
    ProviderConfig,
    ProviderDetails,
    RerankModelConfig,
    RouterModelConfig,
    RouterTargetConfig,
    SubscriptionQuotaConfig,
    UpstreamKeyPoolConfig,
    UpstreamKeySpec,
    UpstreamModelPoolConfig,
    UpstreamRoutingConfig,
    WebDeepResearchModelConfig,
    WebReadModelConfig,
    WebResearchModelConfig,
    WebSearchModelConfig,
    _ModelsOperationConfigSections,
    _TokenPricedOperationModelConfig,
)
from .settings import settings  # noqa: F401
from .validation import (  # noqa: F401
    ANTHROPIC_API_VERSION,
    ENV_REFERENCE_NAME_RE,
    ENV_REFERENCE_RE,
    KNOWN_PROVIDER_ENV_NAMES,
    SUPPORTED_PROXY_SCHEMES,
    ConfigError,
    RuleValidationError,
    _explicit_env_reference_name,
    _looks_like_env_reference,
    _provider_env_reference_error,
    _resolve_explicit_env_reference,
    _warn_unbraced_env_like_literal,
    resolve_provider_api_key,
    resolve_provider_api_keys,
    resolve_provider_api_key_value,
    resolve_provider_config_api_key,
    resolve_provider_config_api_keys,
    resolve_provider_config_auth_headers,
    resolve_provider_proxy,
)


class ConfigLoader(_ConfigLoaderCore):
    """Stable public facade for configuration loading and validation."""
