export const EDITOR_CONSTANTS = Object.freeze({
    MODELS_CACHE_TTL_MS: 15 * 60 * 1000,
    IMAGE_REQUEST_FORMAT_OPTIONS: Object.freeze(['openai_images', 'openai_images_multipart', 'nvidia_genai_json']),
    IMAGE_RESPONSE_FORMAT_OPTIONS: Object.freeze(['openai_images', 'nvidia_artifacts']),
    AUDIO_REQUEST_FORMAT_OPTIONS: Object.freeze(['nvidia_riva_grpc']),
    MAX_SAFE_ERROR_LENGTH: 240,
    STRONG_ETAG_PATTERN: /^"[\x21\x23-\x7E\x80-\xFF]+"$/,
});

export function createEditorState() {
    const documentBases = new Map([
        ['fallback', null],
        ['operation', null],
        ['fusion', null],
        ['router', null],
        ['providers', null],
        ['model', null],
    ]);
    return {
        documentBases,
        loadRequestIds: new Map(Array.from(documentBases.keys(), documentName => [documentName, 0])),
        busyDocuments: new Set(),
        lockedControls: new Map(),
        lockedSubtrees: new Map(),
        lockedDraggables: new Map(),
        evalTabLoadStates: new Map([
            ['openrouter-free', 'idle'],
            ['fallback-eval', 'idle'],
        ]),
        activeEditor: 'rules',
        originalRulesContent: null,
        originalEmbeddingsContent: null,
        originalRerankContent: null,
        originalImagesContent: null,
        originalAudioContent: null,
        originalWebContent: null,
        originalProvidersContent: null,
        originalFusionContent: null,
        originalRouterContent: null,
        originalModelRulesContent: null,
        availableProviders: [],
        embeddingRules: [],
        rerankRules: [],
        imageGenerationRules: [],
        imageEditRules: [],
        audioSpeechRules: [],
        audioTranscriptionRules: [],
        pdfConversionRules: [],
        webSearchRules: [],
        webReadRules: [],
        webResearchRules: [],
        webDeepResearchRules: [],
        gatewayModelCatalog: {
            chat: [],
            embeddings: [],
            images_generations: [],
            web_search: [],
            web_read: [],
        },
        routerFallbackChains: {},
        providerModelsCache: new Map(),
        providerModelsRequests: new Map(),
        providerModelsCacheEpoch: 0,
        providerCatalogControllers: new Set(),
        providerCatalogControllerByRow: new WeakMap(),
        providersLoadState: 'loading',
        providersLoadRequestId: 0,
        saveInFlight: false,
        editorMutationVersion: 0,
        fallbackEvalPollTimer: null,
        openRouterFreePollTimer: null,
        fallbackEvalPollingEnabled: false,
        openRouterFreePollingEnabled: false,
        providerCatalogGeneration: 0,
        rulesTabsController: null,
        activeRulesTabContext: null,
        currentMessage: null,
        localizedBindings: new Set(),
    };
}
