"""Parse generated pip-compile locks and their hash continuation blocks."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from packaging.markers import default_environment
from packaging.requirements import InvalidRequirement, Requirement
from packaging.utils import canonicalize_name
from packaging.version import InvalidVersion, Version


PYTHON_LOCK_VERSION = "3.12"
UNSAFE_OMISSION_FOOTER = (
    "# The following packages are considered to be unsafe in a requirements file:"
)
SHA256_HASH_OPTION_PATTERN = re.compile(
    r"^--hash=sha256:([0-9a-f]{64})(?:\s+\\)?$"
)


def _target_marker_environment() -> dict[str, str]:
    environment = default_environment()
    environment["python_version"] = PYTHON_LOCK_VERSION
    environment["python_full_version"] = f"{PYTHON_LOCK_VERSION}.0"
    return environment


TARGET_MARKER_ENVIRONMENT = _target_marker_environment()


@dataclass(frozen=True)
class ParsedLock:
    filename: str
    pins: dict[str, Version]
    hashes: dict[str, frozenset[str]]


def is_active(requirement: Requirement) -> bool:
    return requirement.marker is None or requirement.marker.evaluate(
        environment=TARGET_MARKER_ENVIRONMENT
    )


def parse_exact_pin(
    line: str,
    *,
    filename: str,
    line_number: int,
    errors: list[str],
) -> tuple[Requirement, Version] | None:
    try:
        requirement = Requirement(line)
    except InvalidRequirement as exc:
        errors.append(f"{filename}:{line_number} is not a valid requirement: {exc}")
        return None

    specifiers = list(requirement.specifier)
    if requirement.url is not None or len(specifiers) != 1:
        errors.append(f"{filename}:{line_number} must contain one exact == pin: {line}")
        return None
    specifier = specifiers[0]
    if specifier.operator != "==" or "*" in specifier.version:
        errors.append(f"{filename}:{line_number} must contain one exact == pin: {line}")
        return None

    try:
        version = Version(specifier.version)
    except InvalidVersion as exc:
        errors.append(f"{filename}:{line_number} has invalid pinned version: {exc}")
        return None
    return requirement, version


def _has_unsafe_omission_footer(lines: list[str]) -> bool:
    for index, line in enumerate(lines):
        if line != UNSAFE_OMISSION_FOOTER:
            continue
        for following_line in lines[index + 1 :]:
            candidate = following_line.strip()
            if not candidate:
                continue
            if candidate in {"# pip", "# setuptools"}:
                return True
            break
    return False


def parse_generated_lock(
    root: Path,
    filename: str,
    errors: list[str],
    *,
    compile_script_command: str,
) -> ParsedLock:
    path = root / filename
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        errors.append(f"Cannot read {filename}: {exc}")
        return ParsedLock(filename=filename, pins={}, hashes={})

    expected_generator = (
        f"# This file is autogenerated by pip-compile with Python {PYTHON_LOCK_VERSION}"
    )
    if expected_generator not in lines[:5]:
        errors.append(
            f"{filename} must declare pip-compile with Python {PYTHON_LOCK_VERSION} in its header"
        )

    expected_command = f"#    {compile_script_command}"
    if expected_command not in lines[:12]:
        errors.append(
            f"{filename} header command differs from the canonical entrypoint: "
            f"{compile_script_command}"
        )
    if _has_unsafe_omission_footer(lines):
        errors.append(
            f"{filename} contains the pip-compile unsafe-omission footer; "
            "installer tooling must be pinned with --allow-unsafe"
        )

    pins: dict[str, Version] = {}
    hashes: dict[str, set[str]] = {}
    current_name: str | None = None
    continuation_open = False
    ignored_continuation = False
    for line_number, raw_line in enumerate(lines, start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            if continuation_open:
                errors.append(
                    f"{filename}:{line_number} interrupts an open hash continuation"
                )
                current_name = None
                continuation_open = False
                ignored_continuation = False
            continue
        if line.startswith("--hash="):
            match = SHA256_HASH_OPTION_PATTERN.fullmatch(line)
            if match is None:
                errors.append(
                    f"{filename}:{line_number} has an invalid SHA-256 hash option"
                )
                current_name = None
                continuation_open = False
                ignored_continuation = False
            elif (
                not continuation_open
                or (current_name is None and not ignored_continuation)
            ):
                errors.append(
                    f"{filename}:{line_number} has a hash without a continued requirement"
                )
                current_name = None
                continuation_open = False
                ignored_continuation = False
            else:
                if current_name is not None:
                    hashes[current_name].add(match.group(1))
                continuation_open = line.endswith("\\")
                if not continuation_open:
                    current_name = None
                    ignored_continuation = False
            continue
        if continuation_open:
            errors.append(
                f"{filename}:{line_number} interrupts an open hash continuation"
            )
            current_name = None
            continuation_open = False
            ignored_continuation = False
        if line.startswith("-"):
            current_name = None
            continuation_open = False
            ignored_continuation = False
            continue
        continuation_open = line.endswith("\\")
        requirement_line = line.removesuffix("\\").rstrip()
        parsed_pin = parse_exact_pin(
            requirement_line,
            filename=filename,
            line_number=line_number,
            errors=errors,
        )
        if parsed_pin is None:
            current_name = None
            continuation_open = False
            ignored_continuation = False
            continue
        requirement, version = parsed_pin
        if not is_active(requirement):
            current_name = None
            ignored_continuation = continuation_open
            continue

        name = canonicalize_name(requirement.name)
        current_name = name
        ignored_continuation = False
        hashes.setdefault(name, set())
        if name in pins:
            errors.append(f"{filename} pins active requirement {name!r} more than once")
            continue
        pins[name] = version

    if continuation_open:
        errors.append(f"{filename}:{len(lines)} ends with an open hash continuation")

    return ParsedLock(
        filename=filename,
        pins=pins,
        hashes={name: frozenset(values) for name, values in hashes.items()},
    )
